---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-tsbe
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  name: hello-tsbe
  namespace: hello-tsbe
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31517
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-tsbe
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-tsbe
  name: hello-tsbe
  namespace: hello-tsbe
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-tsbe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-tsbe
    spec:
      containers:
      - image: ghouscht/tsbe-paas-demo:latest
        imagePullPolicy: Always
        name: hellotsbe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30